apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.com/redhat/centos-stream/containers/bootc?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: "{{revision}}"
    build.appstudio.redhat.com/pull_request_number: "{{pull_request_number}}"
    build.appstudio.redhat.com/target_branch: "{{target_branch}}"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression:
      event == "push" && target_branch == "c10s" && files.all.exists(x,!x.startsWith(".tekton/"))
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: centos-bootc-c10s
    appstudio.openshift.io/component: centos-bootc-c10s
    pipelines.appstudio.openshift.io/type: build
  name: centos-bootc-on-push
  namespace: centos-bootc-tenant
spec:
  timeouts:
    pipeline: "6h0m0s"
    tasks: "4h0m0s"
    finally: "2h0m0s"
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: output-image
      value: quay.io/redhat-user-workloads/centos-bootc-tenant/centos-bootc-c10s/centos-bootc-c10s:{{revision}}
    - name: path-context
      value: .
    - name: revision
      value: "{{revision}}"
  pipelineRef:
    name: buildah-build
  workspaces:
    - name: workspace-amd64
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: workspace-arm64
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
        status: {}
    - name: workspace-ppc64le
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
        status: {}
    - name: workspace-s390x
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
        status: {}
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
status: {}
